language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install coveralls
  - python setup.py install

script:
  - coverage run --source=funcargparse setup.py pytest

after_success:
  coveralls
